#include "BoardConfig.h"
#include "MemConfigBinTool.h"
#include "MemConfigurationTable.h"

#define ENTRY_COUNT 4

MEM_CONFIG_BUSCFG_LP5 MemLpddr5BusCfg = {
  {
    .Signature      = MEM_CONFIG_BLOCK_BUSCFG_LP5_SIGNATURE,
    .BlockSize      = sizeof(MEM_CONFIG_BUSCFG_LP5) + sizeof(MEM_CONFIG_BUSCFG_LP5_ENTRY) * ENTRY_COUNT,
    .BoardMask      = BOARD_ID_MASK_DEFAULT
  },
  {
    //MaxMemFreq        RankPerCh DevWidth CA_ODT   CK_ODT   CS_ODT   DQ_ODT   WCK_ODT  SOC_ODT  NTDQ_ODT ODT_PDDS
    {DDR6400_FREQUENCY, RANK_SR,  DEV_x16, RTT_120, RTT_120, RTT_80,  RTT_80,  RTT_80,  RTT_40,  RTT_OFF,  RTT_40, VREF_AUTO, VREF_AUTO},
    {DDR6400_FREQUENCY, RANK_DR,  DEV_x16, RTT_240, RTT_240, RTT_80,  RTT_120, RTT_120, RTT_40,  RTT_OFF,  RTT_40, VREF_AUTO, VREF_AUTO},
    {DDR6400_FREQUENCY, RANK_SR,  DEV_x8,  RTT_240, RTT_120, RTT_240, RTT_80,  RTT_80,  RTT_40,  RTT_OFF,  RTT_40, VREF_AUTO, VREF_AUTO},
    {DDR6400_FREQUENCY, RANK_DR,  DEV_x8,  0x10,    RTT_240, RTT_240, RTT_120, RTT_120, RTT_40,  RTT_OFF,  RTT_40, VREF_AUTO, VREF_AUTO},
  }
};
