/** @file
 *
 *  Copyright 2024 Cix Technology Group Co., Ltd. All Rights Reserved.
 *
 *  SPDX-License-Identifier: BSD-2-Clause-Patent
 *
 **/

#ifndef __ACPI_RAM_VARIABLE_H__
#define __ACPI_RAM_VARIABLE_H__

#define ARV_PCIE_RP_00_ENABLE_OFFSET        0x00
#define ARV_PCIE_RP_01_ENABLE_OFFSET        0x01
#define ARV_PCIE_RP_02_ENABLE_OFFSET        0x02
#define ARV_PCIE_RP_03_ENABLE_OFFSET        0x03
#define ARV_PCIE_RP_04_ENABLE_OFFSET        0x04
#define ARV_FCH_I2C_0_ENABLE_OFFSET         0x05
#define ARV_FCH_I2C_1_ENABLE_OFFSET         0x06
#define ARV_FCH_I2C_2_ENABLE_OFFSET         0x07
#define ARV_FCH_I2C_3_ENABLE_OFFSET         0x08
#define ARV_FCH_I2C_4_ENABLE_OFFSET         0x09
#define ARV_FCH_I2C_5_ENABLE_OFFSET         0x0A
#define ARV_FCH_I2C_6_ENABLE_OFFSET         0x0B
#define ARV_FCH_I2C_7_ENABLE_OFFSET         0x0C
#define ARV_PCIE_RP_00_LINK_STS_OFFSET      0x0D
#define ARV_PCIE_RP_01_LINK_STS_OFFSET      0x0E
#define ARV_PCIE_RP_02_LINK_STS_OFFSET      0x0F
#define ARV_PCIE_RP_03_LINK_STS_OFFSET      0x10
#define ARV_PCIE_RP_04_LINK_STS_OFFSET      0x11
#define ARV_USB3_TYPEC_DRD_ENABLE_OFFSET    0x12
#define ARV_USB3_TYPEC_HOST0_ENABLE_OFFSET  0x13
#define ARV_USB2_HOST0_ENABLE_OFFSET        0x14
#define ARV_USB3_TYPEC_HOST2_ENABLE_OFFSET  0x15
#define ARV_USB3_TYPEC_HOST1_ENABLE_OFFSET  0x16
#define ARV_USB3_TYPEA_DRD0_ENABLE_OFFSET   0x17
#define ARV_USB3_TYPEA_DRD1_ENABLE_OFFSET   0x18
#define ARV_USB2_HOST3_ENABLE_OFFSET        0x19
#define ARV_USB2_HOST2_ENABLE_OFFSET        0x1A
#define ARV_USB2_HOST1_ENABLE_OFFSET        0x1B
#define ARV_USB3_TYPEC_DRD_ROLE_OFFSET      0x1C
#define ARV_USB3_TYPEA_DRD0_ROLE_OFFSET     0x1D
#define ARV_USB3_TYPEA_DRD1_ROLE_OFFSET     0x1E
#define ARV_CPU_LPI0_ENABLE_OFFSET          0x1F
#define ARV_CPU_LPI1_ENABLE_OFFSET          0x20
#define ARV_CPU_LPI2_ENABLE_OFFSET          0x21
#define ARV_NPU_SUPPORT_INFO_OFFSET         0X22
#define ARV_DPU_00_SUPPORT_OFFSET           0X23
#define ARV_DPU_01_SUPPORT_OFFSET           0X24
#define ARV_DPU_02_SUPPORT_OFFSET           0X25
#define ARV_DPU_03_SUPPORT_OFFSET           0X26
#define ARV_DPU_04_SUPPORT_OFFSET           0X27
#define ARV_AUDIO_SUPPORT_OFFSET            0X28
#define ARV_ISP_SUPPORT_OFFSET              0X29
#define ARV_GMAC0_ENABLE_OFFSET             0x2A
#define ARV_GMAC1_ENABLE_OFFSET             0x2B
#define ARV_FCH_I2C_0_FREQ_OFFSET           0x2C
#define ARV_FCH_I2C_1_FREQ_OFFSET           0x2D
#define ARV_FCH_I2C_2_FREQ_OFFSET           0x2E
#define ARV_FCH_I2C_3_FREQ_OFFSET           0x2F
#define ARV_FCH_I2C_4_FREQ_OFFSET           0x30
#define ARV_FCH_I2C_5_FREQ_OFFSET           0x31
#define ARV_FCH_I2C_6_FREQ_OFFSET           0x32
#define ARV_FCH_I2C_7_FREQ_OFFSET           0x33
#define ARV_PCIE_RP_00_BANDWITCH_OFFSET     0x34
#define ARV_PCIE_RP_01_BANDWITCH_OFFSET     0x35
#define ARV_PCIE_RP_02_BANDWITCH_OFFSET     0x36
#define ARV_PCIE_RP_03_BANDWITCH_OFFSET     0x37
#define ARV_PCIE_RP_04_BANDWITCH_OFFSET     0x38
#define ARV_PCIE_RP_00_MAX_SPEED_OFFSET     0x39
#define ARV_PCIE_RP_01_MAX_SPEED_OFFSET     0x3A
#define ARV_PCIE_RP_02_MAX_SPEED_OFFSET     0x3B
#define ARV_PCIE_RP_03_MAX_SPEED_OFFSET     0x3C
#define ARV_PCIE_RP_04_MAX_SPEED_OFFSET     0x3D
#define ARV_PCIE_RP_00_MAX_PAYLOAD_OFFSET   0x3E
#define ARV_PCIE_RP_01_MAX_PAYLOAD_OFFSET   0x3F
#define ARV_PCIE_RP_02_MAX_PAYLOAD_OFFSET   0x40
#define ARV_PCIE_RP_03_MAX_PAYLOAD_OFFSET   0x41
#define ARV_PCIE_RP_04_MAX_PAYLOAD_OFFSET   0x42
#define ARV_PCIE_RP_00_MAX_ASPM_OFFSET      0x43
#define ARV_PCIE_RP_01_MAX_ASPM_OFFSET      0x44
#define ARV_PCIE_RP_02_MAX_ASPM_OFFSET      0x45
#define ARV_PCIE_RP_03_MAX_ASPM_OFFSET      0x46
#define ARV_PCIE_RP_04_MAX_ASPM_OFFSET      0x47
#define ARV_PCIE_RP_00_ASPM_OFFSET          0x48
#define ARV_PCIE_RP_01_ASPM_OFFSET          0x49
#define ARV_PCIE_RP_02_ASPM_OFFSET          0x4A
#define ARV_PCIE_RP_03_ASPM_OFFSET          0x4B
#define ARV_PCIE_RP_04_ASPM_OFFSET          0x4C

//
#define ARV_VARIABLE_TABLE_TOTAL_SIZE  0x4D

#define ARV_I2C_FREQ_UNIT_HZ   10000

#endif
