/** @file
 *
 *  Copyright 2023 Cix Technology (Shanghai) Co., Ltd. All Rights Reserved.
 *
 *  SPDX-License-Identifier: BSD-2-Clause-Patent
 *
 **/

#ifndef __ACPI_RAM_VARIABLE_H__
#define __ACPI_RAM_VARIABLE_H__

#define ARV_PCIE_RP_00_ENABLE_OFFSET        0x00
#define ARV_PCIE_RP_01_ENABLE_OFFSET        0x01
#define ARV_PCIE_RP_02_ENABLE_OFFSET        0x02
#define ARV_PCIE_RP_03_ENABLE_OFFSET        0x03
#define ARV_PCIE_RP_04_ENABLE_OFFSET        0x04
#define ARV_FCH_I2C_0_ENABLE_OFFSET         0x05
#define ARV_FCH_I2C_1_ENABLE_OFFSET         0x06
#define ARV_FCH_I2C_2_ENABLE_OFFSET         0x07
#define ARV_FCH_I2C_3_ENABLE_OFFSET         0x08
#define ARV_FCH_I2C_4_ENABLE_OFFSET         0x09
#define ARV_FCH_I2C_5_ENABLE_OFFSET         0x0A
#define ARV_FCH_I2C_6_ENABLE_OFFSET         0x0B
#define ARV_FCH_I2C_7_ENABLE_OFFSET         0x0C
#define ARV_PCIE_RP_00_LINK_STS_OFFSET      0x0D
#define ARV_PCIE_RP_01_LINK_STS_OFFSET      0x0E
#define ARV_PCIE_RP_02_LINK_STS_OFFSET      0x0F
#define ARV_PCIE_RP_03_LINK_STS_OFFSET      0x10
#define ARV_PCIE_RP_04_LINK_STS_OFFSET      0x11
#define ARV_USB3_TYPEC_DRD_ENABLE_OFFSET    0x12
#define ARV_USB3_TYPEC_HOST0_ENABLE_OFFSET  0x13
#define ARV_USB2_HOST0_ENABLE_OFFSET        0x14
#define ARV_USB3_TYPEC_HOST2_ENABLE_OFFSET  0x15
#define ARV_USB3_TYPEC_HOST1_ENABLE_OFFSET  0x16
#define ARV_USB3_TYPEA_DRD0_ENABLE_OFFSET   0x17
#define ARV_USB3_TYPEA_DRD1_ENABLE_OFFSET   0x18
#define ARV_USB2_HOST3_ENABLE_OFFSET        0x19
#define ARV_USB2_HOST2_ENABLE_OFFSET        0x1A
#define ARV_USB2_HOST1_ENABLE_OFFSET        0x1B
#define ARV_USB3_TYPEC_DRD_ROLE_OFFSET      0x1C
#define ARV_USB3_TYPEA_DRD0_ROLE_OFFSET     0x1D
#define ARV_USB3_TYPEA_DRD1_ROLE_OFFSET     0x1E
#define ARV_CPU_LPI0_ENABLE_OFFSET          0x1F
#define ARV_CPU_LPI1_ENABLE_OFFSET          0x20
#define ARV_CPU_LPI2_ENABLE_OFFSET          0x21
//
#define ARV_VARIABLE_TABLE_TOTAL_SIZE  0x22
#endif
