/** @file
 *
 *  Copyright 2024 Cix Technology Group Co., Ltd. All Rights Reserved.
 *
 *  SPDX-License-Identifier: BSD-2-Clause-Patent
 *
 **/
// The Arm Gic has no conception of Level-Low but Level-sensitive and Edge-sensitive.
// As this we replace sky1's Level-Low as Level-High which with comment message appended.

#ifndef __INTERRUPT_ID_H__
#define __INTERRUPT_ID_H__

#define CLUSTER_NMPAMNSIRQ_INTERRUPT_ID                                     67
#define CLUSTER_NMPAMNSIRQ_INTERRUPT_TYPE                                   1
#define CLUSTER_NMPAMSIRQ_INTERRUPT_ID                                      68
#define CLUSTER_NMPAMSIRQ_INTERRUPT_TYPE                                    1
#define CLUSTER_CTIIRQ12_INTERRUPT_ID                                       69
#define CLUSTER_CTIIRQ12_INTERRUPT_TYPE                                     1
#define CLUSTER_COREPPUIRQ0_INTERRUPT_ID                                    70
#define CLUSTER_COREPPUIRQ0_INTERRUPT_TYPE                                  1
#define CLUSTER_COREPPUIRQ1_INTERRUPT_ID                                    71
#define CLUSTER_COREPPUIRQ1_INTERRUPT_TYPE                                  1
#define CLUSTER_COREPPUIRQ2_INTERRUPT_ID                                    72
#define CLUSTER_COREPPUIRQ2_INTERRUPT_TYPE                                  1
#define CLUSTER_COREPPUIRQ3_INTERRUPT_ID                                    73
#define CLUSTER_COREPPUIRQ3_INTERRUPT_TYPE                                  1
#define CLUSTER_COREPPUIRQ4_INTERRUPT_ID                                    74
#define CLUSTER_COREPPUIRQ4_INTERRUPT_TYPE                                  1
#define CLUSTER_COREPPUIRQ5_INTERRUPT_ID                                    75
#define CLUSTER_COREPPUIRQ5_INTERRUPT_TYPE                                  1
#define CLUSTER_COREPPUIRQ6_INTERRUPT_ID                                    76
#define CLUSTER_COREPPUIRQ6_INTERRUPT_TYPE                                  1
#define CLUSTER_COREPPUIRQ7_INTERRUPT_ID                                    77
#define CLUSTER_COREPPUIRQ7_INTERRUPT_TYPE                                  1
#define CLUSTER_COREPPUIRQ8_INTERRUPT_ID                                    78
#define CLUSTER_COREPPUIRQ8_INTERRUPT_TYPE                                  1
#define CLUSTER_COREPPUIRQ9_INTERRUPT_ID                                    79
#define CLUSTER_COREPPUIRQ9_INTERRUPT_TYPE                                  1
#define CLUSTER_COREPPUIRQ10_INTERRUPT_ID                                   80
#define CLUSTER_COREPPUIRQ10_INTERRUPT_TYPE                                 1
#define CLUSTER_COREPPUIRQ11_INTERRUPT_ID                                   81
#define CLUSTER_COREPPUIRQ11_INTERRUPT_TYPE                                 1
#define CLUSTER_CLUSTERPPUIRQ_INTERRUPT_ID                                  82
#define CLUSTER_CLUSTERPPUIRQ_INTERRUPT_TYPE                                1
#define CI700_INTREQPMU_NID68_INTERRUPT_ID                                  83
#define CI700_INTREQPMU_NID68_INTERRUPT_TYPE                                1
#define CI700_INTREQERRNS_NID68_INTERRUPT_ID                                84
#define CI700_INTREQERRNS_NID68_INTERRUPT_TYPE                              1
#define CI700_INTREQERRS_NID68_INTERRUPT_ID                                 85
#define CI700_INTREQERRS_NID68_INTERRUPT_TYPE                               1
#define CI700_INTREQFAULTNS_NID68_INTERRUPT_ID                              86
#define CI700_INTREQFAULTNS_NID68_INTERRUPT_TYPE                            1
#define CI700_INTREQFAULTS_NID68_INTERRUPT_ID                               87
#define CI700_INTREQFAULTS_NID68_INTERRUPT_TYPE                             1
#define CI700_INTREQMPAMERRNS_NID68_INTERRUPT_ID                            88
#define CI700_INTREQMPAMERRNS_NID68_INTERRUPT_TYPE                          1
#define CI700_INTREQMPAMERRS_NID68_INTERRUPT_ID                             89
#define CI700_INTREQMPAMERRS_NID68_INTERRUPT_TYPE                           1
#define CI700_INTREQPPU_NID68_INTERRUPT_ID                                  90
#define CI700_INTREQPPU_NID68_INTERRUPT_TYPE                                1
#define CI700_EXT_CI700_RCSU_CI700_RCSU_PPU_IRQ_INTERRUPT_ID                91
#define CI700_EXT_CI700_RCSU_CI700_RCSU_PPU_IRQ_INTERRUPT_TYPE              1
#define NI700_MMHUB_CLK_0_NPMUINTERRUPT_INTERRUPT_ID                        92
#define NI700_MMHUB_CLK_0_NPMUINTERRUPT_INTERRUPT_TYPE                      1 // In Sky1_Interrrupt_IntID_Mapping the Value is Level-Low
#define NI700_MMHUB_PD_0_INTERRUPT_INTERRUPT_ID                             93
#define NI700_MMHUB_PD_0_INTERRUPT_INTERRUPT_TYPE                           1
#define NI700_MMHUB_PD_0_NS_INTERRUPT_INTERRUPT_ID                          94
#define NI700_MMHUB_PD_0_NS_INTERRUPT_INTERRUPT_TYPE                        1
#define NI700_MMHUB_MM_HUB_RCSU_PPU_IRQ_INTERRUPT_ID                        95
#define NI700_MMHUB_MM_HUB_RCSU_PPU_IRQ_INTERRUPT_TYPE                      1
#define NI700_PCIE_CLK_0_NPMUINTERRUPT_INTERRUPT_ID                         96
#define NI700_PCIE_CLK_0_NPMUINTERRUPT_INTERRUPT_TYPE                       1 // In Sky1_Interrrupt_IntID_Mapping the Value is Level-Low
#define NI700_PCIE_PD_0_INTERRUPT_INTERRUPT_ID                              97
#define NI700_PCIE_PD_0_INTERRUPT_INTERRUPT_TYPE                            1
#define NI700_PCIE_PD_0_NS_INTERRUPT_INTERRUPT_ID                           98
#define NI700_PCIE_PD_0_NS_INTERRUPT_INTERRUPT_TYPE                         1
#define NI700_PCIE_PCIE_HUB_RCSU_PPU_IRQ_INTERRUPT_ID                       99
#define NI700_PCIE_PCIE_HUB_RCSU_PPU_IRQ_INTERRUPT_TYPE                     1
#define NI700_SYSHUB_CLK_0_NPMUINTERRUPT_INTERRUPT_ID                       100
#define NI700_SYSHUB_CLK_0_NPMUINTERRUPT_INTERRUPT_TYPE                     1 // In Sky1_Interrrupt_IntID_Mapping the Value is Level-Low
#define NI700_SYSHUB_PD_0_INTERRUPT_INTERRUPT_ID                            101
#define NI700_SYSHUB_PD_0_INTERRUPT_INTERRUPT_TYPE                          1
#define NI700_SYSHUB_PD_0_NS_INTERRUPT_INTERRUPT_ID                         102
#define NI700_SYSHUB_PD_0_NS_INTERRUPT_INTERRUPT_TYPE                       1
#define NI700_SMN_CLK_0_NPMUINTERRUPT_INTERRUPT_ID                          103
#define NI700_SMN_CLK_0_NPMUINTERRUPT_INTERRUPT_TYPE                        1 // In Sky1_Interrrupt_IntID_Mapping the Value is Level-Low
#define NI700_SMN_PD_0_INTERRUPT_INTERRUPT_ID                               104
#define NI700_SMN_PD_0_INTERRUPT_INTERRUPT_TYPE                             1
#define NI700_SMN_PD_0_NS_INTERRUPT_INTERRUPT_ID                            105
#define NI700_SMN_PD_0_NS_INTERRUPT_INTERRUPT_TYPE                          1
#define PCIEHUB_EXT_TCU_EVENT_Q_IRPT_S_INTERRUPT_ID                         106
#define PCIEHUB_EXT_TCU_EVENT_Q_IRPT_S_INTERRUPT_TYPE                       3
#define PCIEHUB_EXT_TCU_EVENT_Q_IRPT_NS_INTERRUPT_ID                        107
#define PCIEHUB_EXT_TCU_EVENT_Q_IRPT_NS_INTERRUPT_TYPE                      3
#define PCIEHUB_EXT_TCU_CMD_SYNC_IRPT_NS_INTERRUPT_ID                       108
#define PCIEHUB_EXT_TCU_CMD_SYNC_IRPT_NS_INTERRUPT_TYPE                     3
#define PCIEHUB_EXT_TCU_CMD_SYNC_IRPT_S_INTERRUPT_ID                        109
#define PCIEHUB_EXT_TCU_CMD_SYNC_IRPT_S_INTERRUPT_TYPE                      3
#define PCIEHUB_EXT_TCU_GLOBAL_IRPT_NS_INTERRUPT_ID                         110
#define PCIEHUB_EXT_TCU_GLOBAL_IRPT_NS_INTERRUPT_TYPE                       3
#define PCIEHUB_EXT_TCU_GLOBAL_IRPT_S_INTERRUPT_ID                          111
#define PCIEHUB_EXT_TCU_GLOBAL_IRPT_S_INTERRUPT_TYPE                        3
#define PCIEHUB_EXT_TCU_RAS_FHI_INTERRUPT_ID                                112
#define PCIEHUB_EXT_TCU_RAS_FHI_INTERRUPT_TYPE                              3
#define PCIEHUB_EXT_TCU_RAS_CRI_INTERRUPT_ID                                113
#define PCIEHUB_EXT_TCU_RAS_CRI_INTERRUPT_TYPE                              3
#define PCIEHUB_EXT_TCU_RAS_ERI_INTERRUPT_ID                                114
#define PCIEHUB_EXT_TCU_RAS_ERI_INTERRUPT_TYPE                              3
#define PCIEHUB_EXT_TCU_PMU_IRPT_INTERRUPT_ID                               115
#define PCIEHUB_EXT_TCU_PMU_IRPT_INTERRUPT_TYPE                             3
#define PCIEHUB_EXT_TCU_PRI_Q_IRPT_NS_INTERRUPT_ID                          116
#define PCIEHUB_EXT_TCU_PRI_Q_IRPT_NS_INTERRUPT_TYPE                        3
#define PCIEHUB_EXT_TBU_RAS_FHI_INTERRUPT_ID                                117
#define PCIEHUB_EXT_TBU_RAS_FHI_INTERRUPT_TYPE                              3
#define PCIEHUB_EXT_TBU_RAS_ERI_INTERRUPT_ID                                118
#define PCIEHUB_EXT_TBU_RAS_ERI_INTERRUPT_TYPE                              3
#define PCIEHUB_EXT_TBU_RAS_CRI_INTERRUPT_ID                                119
#define PCIEHUB_EXT_TBU_RAS_CRI_INTERRUPT_TYPE                              3
#define PCIEHUB_EXT_TBU_PMU_IRPT_INTERRUPT_ID                               120
#define PCIEHUB_EXT_TBU_PMU_IRPT_INTERRUPT_TYPE                             3
#define SYSHUB_EXT_TCU_EVENT_Q_IRPT_S_INTERRUPT_ID                          121
#define SYSHUB_EXT_TCU_EVENT_Q_IRPT_S_INTERRUPT_TYPE                        3
#define SYSHUB_EXT_TCU_EVENT_Q_IRPT_NS_INTERRUPT_ID                         122
#define SYSHUB_EXT_TCU_EVENT_Q_IRPT_NS_INTERRUPT_TYPE                       3
#define SYSHUB_EXT_TCU_CMD_SYNC_IRPT_NS_INTERRUPT_ID                        123
#define SYSHUB_EXT_TCU_CMD_SYNC_IRPT_NS_INTERRUPT_TYPE                      3
#define SYSHUB_EXT_TCU_CMD_SYNC_IRPT_S_INTERRUPT_ID                         124
#define SYSHUB_EXT_TCU_CMD_SYNC_IRPT_S_INTERRUPT_TYPE                       3
#define SYSHUB_EXT_TCU_GLOBAL_IRPT_NS_INTERRUPT_ID                          125
#define SYSHUB_EXT_TCU_GLOBAL_IRPT_NS_INTERRUPT_TYPE                        3
#define SYSHUB_EXT_TCU_GLOBAL_IRPT_S_INTERRUPT_ID                           126
#define SYSHUB_EXT_TCU_GLOBAL_IRPT_S_INTERRUPT_TYPE                         3
#define SYSHUB_EXT_TCU_RAS_FHI_INTERRUPT_ID                                 127
#define SYSHUB_EXT_TCU_RAS_FHI_INTERRUPT_TYPE                               3
#define SYSHUB_EXT_TCU_RAS_CRI_INTERRUPT_ID                                 128
#define SYSHUB_EXT_TCU_RAS_CRI_INTERRUPT_TYPE                               3
#define SYSHUB_EXT_TCU_RAS_ERI_INTERRUPT_ID                                 129
#define SYSHUB_EXT_TCU_RAS_ERI_INTERRUPT_TYPE                               3
#define SYSHUB_EXT_TCU_PMU_IRPT_INTERRUPT_ID                                130
#define SYSHUB_EXT_TCU_PMU_IRPT_INTERRUPT_TYPE                              3
#define SYSHUB_EXT_TCU_PRI_Q_IRPT_NS_INTERRUPT_ID                           131
#define SYSHUB_EXT_TCU_PRI_Q_IRPT_NS_INTERRUPT_TYPE                         3
#define SYSHUB_EXT_TBU_0_RAS_FHI_INTERRUPT_ID                               132
#define SYSHUB_EXT_TBU_0_RAS_FHI_INTERRUPT_TYPE                             3
#define SYSHUB_EXT_TBU_0_RAS_ERI_INTERRUPT_ID                               133
#define SYSHUB_EXT_TBU_0_RAS_ERI_INTERRUPT_TYPE                             3
#define SYSHUB_EXT_TBU_0_RAS_CRI_INTERRUPT_ID                               134
#define SYSHUB_EXT_TBU_0_RAS_CRI_INTERRUPT_TYPE                             3
#define SYSHUB_EXT_TBU_0_PMU_IRPT_INTERRUPT_ID                              135
#define SYSHUB_EXT_TBU_0_PMU_IRPT_INTERRUPT_TYPE                            3
#define SYSHUB_EXT_TBU_1_RAS_FHI_INTERRUPT_ID                               136
#define SYSHUB_EXT_TBU_1_RAS_FHI_INTERRUPT_TYPE                             3
#define SYSHUB_EXT_TBU_1_RAS_ERI_INTERRUPT_ID                               137
#define SYSHUB_EXT_TBU_1_RAS_ERI_INTERRUPT_TYPE                             3
#define SYSHUB_EXT_TBU_1_RAS_CRI_INTERRUPT_ID                               138
#define SYSHUB_EXT_TBU_1_RAS_CRI_INTERRUPT_TYPE                             3
#define SYSHUB_EXT_TBU_1_PMU_IRPT_INTERRUPT_ID                              139
#define SYSHUB_EXT_TBU_1_PMU_IRPT_INTERRUPT_TYPE                            3
#define MMHUB_EXT_TCU_EVENT_Q_IRPT_S_INTERRUPT_ID                           140
#define MMHUB_EXT_TCU_EVENT_Q_IRPT_S_INTERRUPT_TYPE                         3
#define MMHUB_EXT_TCU_EVENT_Q_IRPT_NS_INTERRUPT_ID                          141
#define MMHUB_EXT_TCU_EVENT_Q_IRPT_NS_INTERRUPT_TYPE                        3
#define MMHUB_EXT_TCU_CMD_SYNC_IRPT_NS_INTERRUPT_ID                         142
#define MMHUB_EXT_TCU_CMD_SYNC_IRPT_NS_INTERRUPT_TYPE                       3
#define MMHUB_EXT_TCU_CMD_SYNC_IRPT_S_INTERRUPT_ID                          143
#define MMHUB_EXT_TCU_CMD_SYNC_IRPT_S_INTERRUPT_TYPE                        3
#define MMHUB_EXT_TCU_GLOBAL_IRPT_NS_INTERRUPT_ID                           144
#define MMHUB_EXT_TCU_GLOBAL_IRPT_NS_INTERRUPT_TYPE                         3
#define MMHUB_EXT_TCU_GLOBAL_IRPT_S_INTERRUPT_ID                            145
#define MMHUB_EXT_TCU_GLOBAL_IRPT_S_INTERRUPT_TYPE                          3
#define MMHUB_EXT_TCU_RAS_FHI_INTERRUPT_ID                                  146
#define MMHUB_EXT_TCU_RAS_FHI_INTERRUPT_TYPE                                3
#define MMHUB_EXT_TCU_RAS_CRI_INTERRUPT_ID                                  147
#define MMHUB_EXT_TCU_RAS_CRI_INTERRUPT_TYPE                                3
#define MMHUB_EXT_TCU_RAS_ERI_INTERRUPT_ID                                  148
#define MMHUB_EXT_TCU_RAS_ERI_INTERRUPT_TYPE                                3
#define MMHUB_EXT_TCU_PMU_IRPT_INTERRUPT_ID                                 149
#define MMHUB_EXT_TCU_PMU_IRPT_INTERRUPT_TYPE                               3
#define MMHUB_EXT_TCU_PRI_Q_IRPT_NS_INTERRUPT_ID                            150
#define MMHUB_EXT_TCU_PRI_Q_IRPT_NS_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU0_TBU0_RAS_FHI_INTERRUPT_ID                            151
#define MMHUB_EXT_DPU0_TBU0_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU0_TBU0_RAS_ERI_INTERRUPT_ID                            152
#define MMHUB_EXT_DPU0_TBU0_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU0_TBU0_RAS_CRI_INTERRUPT_ID                            153
#define MMHUB_EXT_DPU0_TBU0_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU0_TBU0_PMU_IRPT_INTERRUPT_ID                           154
#define MMHUB_EXT_DPU0_TBU0_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU0_TBU1_RAS_FHI_INTERRUPT_ID                            155
#define MMHUB_EXT_DPU0_TBU1_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU0_TBU1_RAS_ERI_INTERRUPT_ID                            156
#define MMHUB_EXT_DPU0_TBU1_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU0_TBU1_RAS_CRI_INTERRUPT_ID                            157
#define MMHUB_EXT_DPU0_TBU1_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU0_TBU1_PMU_IRPT_INTERRUPT_ID                           158
#define MMHUB_EXT_DPU0_TBU1_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU0_TBU2_RAS_FHI_INTERRUPT_ID                            159
#define MMHUB_EXT_DPU0_TBU2_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU0_TBU2_RAS_ERI_INTERRUPT_ID                            160
#define MMHUB_EXT_DPU0_TBU2_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU0_TBU2_RAS_CRI_INTERRUPT_ID                            161
#define MMHUB_EXT_DPU0_TBU2_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU0_TBU2_PMU_IRPT_INTERRUPT_ID                           162
#define MMHUB_EXT_DPU0_TBU2_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU1_TBU0_RAS_FHI_INTERRUPT_ID                            163
#define MMHUB_EXT_DPU1_TBU0_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU1_TBU0_RAS_ERI_INTERRUPT_ID                            164
#define MMHUB_EXT_DPU1_TBU0_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU1_TBU0_RAS_CRI_INTERRUPT_ID                            165
#define MMHUB_EXT_DPU1_TBU0_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU1_TBU0_PMU_IRPT_INTERRUPT_ID                           166
#define MMHUB_EXT_DPU1_TBU0_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU1_TBU1_RAS_FHI_INTERRUPT_ID                            167
#define MMHUB_EXT_DPU1_TBU1_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU1_TBU1_RAS_ERI_INTERRUPT_ID                            168
#define MMHUB_EXT_DPU1_TBU1_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU1_TBU1_RAS_CRI_INTERRUPT_ID                            169
#define MMHUB_EXT_DPU1_TBU1_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU1_TBU1_PMU_IRPT_INTERRUPT_ID                           170
#define MMHUB_EXT_DPU1_TBU1_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU1_TBU2_RAS_FHI_INTERRUPT_ID                            171
#define MMHUB_EXT_DPU1_TBU2_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU1_TBU2_RAS_ERI_INTERRUPT_ID                            172
#define MMHUB_EXT_DPU1_TBU2_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU1_TBU2_RAS_CRI_INTERRUPT_ID                            173
#define MMHUB_EXT_DPU1_TBU2_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU1_TBU2_PMU_IRPT_INTERRUPT_ID                           174
#define MMHUB_EXT_DPU1_TBU2_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU2_TBU0_RAS_FHI_INTERRUPT_ID                            175
#define MMHUB_EXT_DPU2_TBU0_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU2_TBU0_RAS_ERI_INTERRUPT_ID                            176
#define MMHUB_EXT_DPU2_TBU0_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU2_TBU0_RAS_CRI_INTERRUPT_ID                            177
#define MMHUB_EXT_DPU2_TBU0_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU2_TBU0_PMU_IRPT_INTERRUPT_ID                           178
#define MMHUB_EXT_DPU2_TBU0_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU2_TBU1_RAS_FHI_INTERRUPT_ID                            179
#define MMHUB_EXT_DPU2_TBU1_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU2_TBU1_RAS_ERI_INTERRUPT_ID                            180
#define MMHUB_EXT_DPU2_TBU1_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU2_TBU1_RAS_CRI_INTERRUPT_ID                            181
#define MMHUB_EXT_DPU2_TBU1_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU2_TBU1_PMU_IRPT_INTERRUPT_ID                           182
#define MMHUB_EXT_DPU2_TBU1_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU2_TBU2_RAS_FHI_INTERRUPT_ID                            183
#define MMHUB_EXT_DPU2_TBU2_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU2_TBU2_RAS_ERI_INTERRUPT_ID                            184
#define MMHUB_EXT_DPU2_TBU2_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU2_TBU2_RAS_CRI_INTERRUPT_ID                            185
#define MMHUB_EXT_DPU2_TBU2_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU2_TBU2_PMU_IRPT_INTERRUPT_ID                           186
#define MMHUB_EXT_DPU2_TBU2_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU3_TBU0_RAS_FHI_INTERRUPT_ID                            187
#define MMHUB_EXT_DPU3_TBU0_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU3_TBU0_RAS_ERI_INTERRUPT_ID                            188
#define MMHUB_EXT_DPU3_TBU0_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU3_TBU0_RAS_CRI_INTERRUPT_ID                            189
#define MMHUB_EXT_DPU3_TBU0_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU3_TBU0_PMU_IRPT_INTERRUPT_ID                           190
#define MMHUB_EXT_DPU3_TBU0_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU3_TBU1_RAS_FHI_INTERRUPT_ID                            191
#define MMHUB_EXT_DPU3_TBU1_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU3_TBU1_RAS_ERI_INTERRUPT_ID                            192
#define MMHUB_EXT_DPU3_TBU1_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU3_TBU1_RAS_CRI_INTERRUPT_ID                            193
#define MMHUB_EXT_DPU3_TBU1_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU3_TBU1_PMU_IRPT_INTERRUPT_ID                           194
#define MMHUB_EXT_DPU3_TBU1_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU3_TBU2_RAS_FHI_INTERRUPT_ID                            195
#define MMHUB_EXT_DPU3_TBU2_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU3_TBU2_RAS_ERI_INTERRUPT_ID                            196
#define MMHUB_EXT_DPU3_TBU2_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU3_TBU2_RAS_CRI_INTERRUPT_ID                            197
#define MMHUB_EXT_DPU3_TBU2_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU3_TBU2_PMU_IRPT_INTERRUPT_ID                           198
#define MMHUB_EXT_DPU3_TBU2_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU4_TBU0_RAS_FHI_INTERRUPT_ID                            199
#define MMHUB_EXT_DPU4_TBU0_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU4_TBU0_RAS_ERI_INTERRUPT_ID                            200
#define MMHUB_EXT_DPU4_TBU0_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU4_TBU0_RAS_CRI_INTERRUPT_ID                            201
#define MMHUB_EXT_DPU4_TBU0_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU4_TBU0_PMU_IRPT_INTERRUPT_ID                           202
#define MMHUB_EXT_DPU4_TBU0_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU4_TBU1_RAS_FHI_INTERRUPT_ID                            203
#define MMHUB_EXT_DPU4_TBU1_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU4_TBU1_RAS_ERI_INTERRUPT_ID                            204
#define MMHUB_EXT_DPU4_TBU1_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU4_TBU1_RAS_CRI_INTERRUPT_ID                            205
#define MMHUB_EXT_DPU4_TBU1_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU4_TBU1_PMU_IRPT_INTERRUPT_ID                           206
#define MMHUB_EXT_DPU4_TBU1_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_DPU4_TBU2_RAS_FHI_INTERRUPT_ID                            207
#define MMHUB_EXT_DPU4_TBU2_RAS_FHI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU4_TBU2_RAS_ERI_INTERRUPT_ID                            208
#define MMHUB_EXT_DPU4_TBU2_RAS_ERI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU4_TBU2_RAS_CRI_INTERRUPT_ID                            209
#define MMHUB_EXT_DPU4_TBU2_RAS_CRI_INTERRUPT_TYPE                          3
#define MMHUB_EXT_DPU4_TBU2_PMU_IRPT_INTERRUPT_ID                           210
#define MMHUB_EXT_DPU4_TBU2_PMU_IRPT_INTERRUPT_TYPE                         3
#define MMHUB_EXT_NPU_TBU0_RAS_FHI_INTERRUPT_ID                             211
#define MMHUB_EXT_NPU_TBU0_RAS_FHI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_NPU_TBU0_RAS_ERI_INTERRUPT_ID                             212
#define MMHUB_EXT_NPU_TBU0_RAS_ERI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_NPU_TBU0_RAS_CRI_INTERRUPT_ID                             213
#define MMHUB_EXT_NPU_TBU0_RAS_CRI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_NPU_TBU0_PMU_IRPT_INTERRUPT_ID                            214
#define MMHUB_EXT_NPU_TBU0_PMU_IRPT_INTERRUPT_TYPE                          3
#define MMHUB_EXT_NPU_TBU1_RAS_FHI_INTERRUPT_ID                             215
#define MMHUB_EXT_NPU_TBU1_RAS_FHI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_NPU_TBU1_RAS_ERI_INTERRUPT_ID                             216
#define MMHUB_EXT_NPU_TBU1_RAS_ERI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_NPU_TBU1_RAS_CRI_INTERRUPT_ID                             217
#define MMHUB_EXT_NPU_TBU1_RAS_CRI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_NPU_TBU1_PMU_IRPT_INTERRUPT_ID                            218
#define MMHUB_EXT_NPU_TBU1_PMU_IRPT_INTERRUPT_TYPE                          3
#define MMHUB_EXT_ISP_TBU0_RAS_FHI_INTERRUPT_ID                             219
#define MMHUB_EXT_ISP_TBU0_RAS_FHI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_ISP_TBU0_RAS_ERI_INTERRUPT_ID                             220
#define MMHUB_EXT_ISP_TBU0_RAS_ERI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_ISP_TBU0_RAS_CRI_INTERRUPT_ID                             221
#define MMHUB_EXT_ISP_TBU0_RAS_CRI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_ISP_TBU0_PMU_IRPT_INTERRUPT_ID                            222
#define MMHUB_EXT_ISP_TBU0_PMU_IRPT_INTERRUPT_TYPE                          3
#define MMHUB_EXT_ISP_TBU1_RAS_FHI_INTERRUPT_ID                             223
#define MMHUB_EXT_ISP_TBU1_RAS_FHI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_ISP_TBU1_RAS_ERI_INTERRUPT_ID                             224
#define MMHUB_EXT_ISP_TBU1_RAS_ERI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_ISP_TBU1_RAS_CRI_INTERRUPT_ID                             225
#define MMHUB_EXT_ISP_TBU1_RAS_CRI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_ISP_TBU1_PMU_IRPT_INTERRUPT_ID                            226
#define MMHUB_EXT_ISP_TBU1_PMU_IRPT_INTERRUPT_TYPE                          3
#define MMHUB_EXT_ISP_TBU2_RAS_FHI_INTERRUPT_ID                             227
#define MMHUB_EXT_ISP_TBU2_RAS_FHI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_ISP_TBU2_RAS_ERI_INTERRUPT_ID                             228
#define MMHUB_EXT_ISP_TBU2_RAS_ERI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_ISP_TBU2_RAS_CRI_INTERRUPT_ID                             229
#define MMHUB_EXT_ISP_TBU2_RAS_CRI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_ISP_TBU2_PMU_IRPT_INTERRUPT_ID                            230
#define MMHUB_EXT_ISP_TBU2_PMU_IRPT_INTERRUPT_TYPE                          3
#define MMHUB_EXT_CSI_TBU0_RAS_FHI_INTERRUPT_ID                             231
#define MMHUB_EXT_CSI_TBU0_RAS_FHI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_CSI_TBU0_RAS_ERI_INTERRUPT_ID                             232
#define MMHUB_EXT_CSI_TBU0_RAS_ERI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_CSI_TBU0_RAS_CRI_INTERRUPT_ID                             233
#define MMHUB_EXT_CSI_TBU0_RAS_CRI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_CSI_TBU0_PMU_IRPT_INTERRUPT_ID                            234
#define MMHUB_EXT_CSI_TBU0_PMU_IRPT_INTERRUPT_TYPE                          3
#define MMHUB_EXT_CSI_TBU1_RAS_FHI_INTERRUPT_ID                             235
#define MMHUB_EXT_CSI_TBU1_RAS_FHI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_CSI_TBU1_RAS_ERI_INTERRUPT_ID                             236
#define MMHUB_EXT_CSI_TBU1_RAS_ERI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_CSI_TBU1_RAS_CRI_INTERRUPT_ID                             237
#define MMHUB_EXT_CSI_TBU1_RAS_CRI_INTERRUPT_TYPE                           3
#define MMHUB_EXT_CSI_TBU1_PMU_IRPT_INTERRUPT_ID                            238
#define MMHUB_EXT_CSI_TBU1_PMU_IRPT_INTERRUPT_TYPE                          3
#define DDR_CH0_DDRC_0_CONTROLLER_INT_INTERRUPT_ID                          239
#define DDR_CH0_DDRC_0_CONTROLLER_INT_INTERRUPT_TYPE                        1
#define DDR_CH0_UMC_PI_INT_DDRP_0_INTERRUPT_ID                              240
#define DDR_CH0_UMC_PI_INT_DDRP_0_INTERRUPT_TYPE                            1
#define DDR_CH0_TZC400_INT_0_INTERRUPT_ID                                   241
#define DDR_CH0_TZC400_INT_0_INTERRUPT_TYPE                                 1
#define DDR_CH1_DDRC_1_CONTROLLER_INT_INTERRUPT_ID                          242
#define DDR_CH1_DDRC_1_CONTROLLER_INT_INTERRUPT_TYPE                        1
#define DDR_CH1_UMC_PI_INT_DDRP_1_INTERRUPT_ID                              243
#define DDR_CH1_UMC_PI_INT_DDRP_1_INTERRUPT_TYPE                            1
#define DDR_CH1_TZC400_INT_1_INTERRUPT_ID                                   244
#define DDR_CH1_TZC400_INT_1_INTERRUPT_TYPE                                 1
#define DDR_CH2_DDRC_2_CONTROLLER_INT_INTERRUPT_ID                          245
#define DDR_CH2_DDRC_2_CONTROLLER_INT_INTERRUPT_TYPE                        1
#define DDR_CH2_UMC_PI_INT_DDRP_2_INTERRUPT_ID                              246
#define DDR_CH2_UMC_PI_INT_DDRP_2_INTERRUPT_TYPE                            1
#define DDR_CH2_TZC400_INT_2_INTERRUPT_ID                                   247
#define DDR_CH2_TZC400_INT_2_INTERRUPT_TYPE                                 1
#define DDR_CH3_DDRC_3_CONTROLLER_INT_INTERRUPT_ID                          248
#define DDR_CH3_DDRC_3_CONTROLLER_INT_INTERRUPT_TYPE                        1
#define DDR_CH3_UMC_PI_INT_DDRP_3_INTERRUPT_ID                              249
#define DDR_CH3_UMC_PI_INT_DDRP_3_INTERRUPT_TYPE                            1
#define DDR_CH3_TZC400_INT_3_INTERRUPT_ID                                   250
#define DDR_CH3_TZC400_INT_3_INTERRUPT_TYPE                                 1
#define AUDIO_IRQ_O_I2S_SC0_INTERRUPT_ID                                    251
#define AUDIO_IRQ_O_I2S_SC0_INTERRUPT_TYPE                                  1
#define AUDIO_IRQ_O_I2S_SC1_INTERRUPT_ID                                    252
#define AUDIO_IRQ_O_I2S_SC1_INTERRUPT_TYPE                                  1
#define AUDIO_IRQ_O_I2S_SC2_INTERRUPT_ID                                    253
#define AUDIO_IRQ_O_I2S_SC2_INTERRUPT_TYPE                                  1
#define AUDIO_IRQ_O_I2S_MC2A_INTERRUPT_ID                                   254
#define AUDIO_IRQ_O_I2S_MC2A_INTERRUPT_TYPE                                 1
#define AUDIO_IRQ_O_I2S_MC2B_INTERRUPT_ID                                   255
#define AUDIO_IRQ_O_I2S_MC2B_INTERRUPT_TYPE                                 1
#define AUDIO_IRQ_O_I2S_MC5A_INTERRUPT_ID                                   256
#define AUDIO_IRQ_O_I2S_MC5A_INTERRUPT_TYPE                                 1
#define AUDIO_IRQ_O_I2S_MC5B_INTERRUPT_ID                                   257
#define AUDIO_IRQ_O_I2S_MC5B_INTERRUPT_TYPE                                 1
#define AUDIO_IRQ_O_I2S_MC5C_INTERRUPT_ID                                   258
#define AUDIO_IRQ_O_I2S_MC5C_INTERRUPT_TYPE                                 1
#define AUDIO_IRQ_O_I2S_MC5D_INTERRUPT_ID                                   259
#define AUDIO_IRQ_O_I2S_MC5D_INTERRUPT_TYPE                                 1
#define AUDIO_IRQ_O_I2S_MC5E_INTERRUPT_ID                                   260
#define AUDIO_IRQ_O_I2S_MC5E_INTERRUPT_TYPE                                 1
#define AUDIO_IRQ_O_WDT_INTERRUPT_ID                                        261
#define AUDIO_IRQ_O_WDT_INTERRUPT_TYPE                                      1
#define AUDIO_IRQ_O_AP_DMA_INTERRUPT_ID                                     262
#define AUDIO_IRQ_O_AP_DMA_INTERRUPT_TYPE                                   1
#define AUDIO_IRQ_O_AUDIO_SW_INTERRUPT_ID                                   263
#define AUDIO_IRQ_O_AUDIO_SW_INTERRUPT_TYPE                                 1
#define AUDIO_IRQ_O_MAILBOX0_CALLER_INTERRUPT_ID                            264
#define AUDIO_IRQ_O_MAILBOX0_CALLER_INTERRUPT_TYPE                          1
#define AUDIO_IRQ_O_MAILBOX1_CALLEE_INTERRUPT_ID                            265
#define AUDIO_IRQ_O_MAILBOX1_CALLEE_INTERRUPT_TYPE                          1
#define AUDIO_IRQ_O_HDA_INTERRUPT_ID                                        266
#define AUDIO_IRQ_O_HDA_INTERRUPT_TYPE                                      1
#define GPU_EXT_GPU_DESIGN_CTIIRQ0_INTERRUPT_ID                             267
#define GPU_EXT_GPU_DESIGN_CTIIRQ0_INTERRUPT_TYPE                           1
#define GPU_EXT_GPU_DESIGN_CTIIRQ1_INTERRUPT_ID                             268
#define GPU_EXT_GPU_DESIGN_CTIIRQ1_INTERRUPT_TYPE                           1
#define GPU_EXT_VDCI_GPU_MISC_VDDGPU_VDDSOC_IRQJOB_VDCI_OUT_INTERRUPT_ID    269
#define GPU_EXT_VDCI_GPU_MISC_VDDGPU_VDDSOC_IRQJOB_VDCI_OUT_INTERRUPT_TYPE  1
#define GPU_EXT_VDCI_GPU_MISC_VDDGPU_VDDSOC_IRQMMU_VDCI_OUT_INTERRUPT_ID    270
#define GPU_EXT_VDCI_GPU_MISC_VDDGPU_VDDSOC_IRQMMU_VDCI_OUT_INTERRUPT_TYPE  1
#define GPU_EXT_VDCI_GPU_MISC_VDDGPU_VDDSOC_IRQGPU_VDCI_OUT_INTERRUPT_ID    271
#define GPU_EXT_VDCI_GPU_MISC_VDDGPU_VDDSOC_IRQGPU_VDCI_OUT_INTERRUPT_TYPE  1
#define USB2_HOST0_U2_HOST0_IRQ_INTERRUPT_ID                                272
#define USB2_HOST0_U2_HOST0_IRQ_INTERRUPT_TYPE                              1
#define USB2_HOST0_U2_HOST0_OTGIRQ_INTERRUPT_ID                             273
#define USB2_HOST0_U2_HOST0_OTGIRQ_INTERRUPT_TYPE                           1
#define USB2_HOST0_U2_HOST0_HOST_SYSTEM_ERROR_INTERRUPT_ID                  274
#define USB2_HOST0_U2_HOST0_HOST_SYSTEM_ERROR_INTERRUPT_TYPE                1
#define USB2_HOST1_U2_HOST1_IRQ_INTERRUPT_ID                                275
#define USB2_HOST1_U2_HOST1_IRQ_INTERRUPT_TYPE                              1
#define USB2_HOST1_U2_HOST1_OTGIRQ_INTERRUPT_ID                             276
#define USB2_HOST1_U2_HOST1_OTGIRQ_INTERRUPT_TYPE                           1
#define USB2_HOST1_U2_HOST1_HOST_SYSTEM_ERROR_INTERRUPT_ID                  277
#define USB2_HOST1_U2_HOST1_HOST_SYSTEM_ERROR_INTERRUPT_TYPE                1
#define USB2_HOST2_U2_HOST2_IRQ_INTERRUPT_ID                                278
#define USB2_HOST2_U2_HOST2_IRQ_INTERRUPT_TYPE                              1
#define USB2_HOST2_U2_HOST2_OTGIRQ_INTERRUPT_ID                             279
#define USB2_HOST2_U2_HOST2_OTGIRQ_INTERRUPT_TYPE                           1
#define USB2_HOST2_U2_HOST2_HOST_SYSTEM_ERROR_INTERRUPT_ID                  280
#define USB2_HOST2_U2_HOST2_HOST_SYSTEM_ERROR_INTERRUPT_TYPE                1
#define USB2_HOST3_U2_HOST3_IRQ_INTERRUPT_ID                                281
#define USB2_HOST3_U2_HOST3_IRQ_INTERRUPT_TYPE                              1
#define USB2_HOST3_U2_HOST3_OTGIRQ_INTERRUPT_ID                             282
#define USB2_HOST3_U2_HOST3_OTGIRQ_INTERRUPT_TYPE                           1
#define USB2_HOST3_U2_HOST3_HOST_SYSTEM_ERROR_INTERRUPT_ID                  283
#define USB2_HOST3_U2_HOST3_HOST_SYSTEM_ERROR_INTERRUPT_TYPE                1
#define USB3_TYPEA_CTL0_U3_TYPEA_CTL0_IRQ_INTERRUPT_ID                      284
#define USB3_TYPEA_CTL0_U3_TYPEA_CTL0_IRQ_INTERRUPT_TYPE                    1
#define USB3_TYPEA_CTL0_U3_TYPEA_CTL0_OTGIRQ_INTERRUPT_ID                   285
#define USB3_TYPEA_CTL0_U3_TYPEA_CTL0_OTGIRQ_INTERRUPT_TYPE                 1
#define USB3_TYPEA_CTL0_U3_TYPEA_CTL0_HOST_SYSTEM_ERROR_INTERRUPT_ID        286
#define USB3_TYPEA_CTL0_U3_TYPEA_CTL0_HOST_SYSTEM_ERROR_INTERRUPT_TYPE      1
#define USB3_TYPEA_CTL0_U3_TYPEA_CTL0_ITP_INTERRUPT_ID                      287
#define USB3_TYPEA_CTL0_U3_TYPEA_CTL0_ITP_INTERRUPT_TYPE                    3
#define USB3_TYPEA_PHY0_U3_TYPEA_SD0803_PHY_INTERRUPT_LN_0_INTERRUPT_ID     288
#define USB3_TYPEA_PHY0_U3_TYPEA_SD0803_PHY_INTERRUPT_LN_0_INTERRUPT_TYPE   1
#define USB3_TYPEA_CTL1_U3_TYPEA_CTL1_IRQ_INTERRUPT_ID                      289
#define USB3_TYPEA_CTL1_U3_TYPEA_CTL1_IRQ_INTERRUPT_TYPE                    1
#define USB3_TYPEA_CTL1_U3_TYPEA_CTL1_OTGIRQ_INTERRUPT_ID                   290
#define USB3_TYPEA_CTL1_U3_TYPEA_CTL1_OTGIRQ_INTERRUPT_TYPE                 1
#define USB3_TYPEA_CTL1_U3_TYPEA_CTL1_HOST_SYSTEM_ERROR_INTERRUPT_ID        291
#define USB3_TYPEA_CTL1_U3_TYPEA_CTL1_HOST_SYSTEM_ERROR_INTERRUPT_TYPE      1
#define USB3_TYPEA_CTL1_U3_TYPEA_CTL1_ITP_INTERRUPT_ID                      292
#define USB3_TYPEA_CTL1_U3_TYPEA_CTL1_ITP_INTERRUPT_TYPE                    3
#define USB3_TYPEA_PHY1_U3_TYPEA_SD0803_PHY_INTERRUPT_LN_1_INTERRUPT_ID     293
#define USB3_TYPEA_PHY1_U3_TYPEA_SD0803_PHY_INTERRUPT_LN_1_INTERRUPT_TYPE   1
#define USB3_TYPEC_U3_TYPEC_DRD_IRQ_INTERRUPT_ID                            294
#define USB3_TYPEC_U3_TYPEC_DRD_IRQ_INTERRUPT_TYPE                          1
#define USB3_TYPEC_U3_TYPEC_DRD_OTGIRQ_INTERRUPT_ID                         295
#define USB3_TYPEC_U3_TYPEC_DRD_OTGIRQ_INTERRUPT_TYPE                       1
#define USB3_TYPEC_U3_TYPEC_DRD_HOST_SYSTEM_ERROR_INTERRUPT_ID              296
#define USB3_TYPEC_U3_TYPEC_DRD_HOST_SYSTEM_ERROR_INTERRUPT_TYPE            1
#define USB3_TYPEC_U3_TYPEC_DRD_ITP_INTERRUPT_ID                            297
#define USB3_TYPEC_U3_TYPEC_DRD_ITP_INTERRUPT_TYPE                          3
#define USB3_TYPEC_U3_TYPEC_DRD_PHY_INTERRUPT_DP_INTERRUPT_ID               298
#define USB3_TYPEC_U3_TYPEC_DRD_PHY_INTERRUPT_DP_INTERRUPT_TYPE             1
#define USB3_TYPEC_U3_TYPEC_DRD_PHY_INTERRUPT_USB_INTERRUPT_ID              299
#define USB3_TYPEC_U3_TYPEC_DRD_PHY_INTERRUPT_USB_INTERRUPT_TYPE            1
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_IRQ_INTERRUPT_ID                    300
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_IRQ_INTERRUPT_TYPE                  1
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_OTGIRQ_INTERRUPT_ID                 301
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_OTGIRQ_INTERRUPT_TYPE               1
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_HOST_SYSTEM_ERROR_INTERRUPT_ID      302
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_HOST_SYSTEM_ERROR_INTERRUPT_TYPE    1
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_ITP_INTERRUPT_ID                    303
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_ITP_INTERRUPT_TYPE                  3
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_PHY_INTERRUPT_DP_INTERRUPT_ID       304
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_PHY_INTERRUPT_DP_INTERRUPT_TYPE     1
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_PHY_INTERRUPT_USB_INTERRUPT_ID      305
#define USB3_TYPEC_HOST0_U3_TYPEC_HOST0_PHY_INTERRUPT_USB_INTERRUPT_TYPE    1
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_IRQ_INTERRUPT_ID                    306
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_IRQ_INTERRUPT_TYPE                  1
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_OTGIRQ_INTERRUPT_ID                 307
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_OTGIRQ_INTERRUPT_TYPE               1
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_HOST_SYSTEM_ERROR_INTERRUPT_ID      308
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_HOST_SYSTEM_ERROR_INTERRUPT_TYPE    1
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_ITP_INTERRUPT_ID                    309
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_ITP_INTERRUPT_TYPE                  3
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_PHY_INTERRUPT_DP_INTERRUPT_ID       310
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_PHY_INTERRUPT_DP_INTERRUPT_TYPE     1
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_PHY_INTERRUPT_USB_INTERRUPT_ID      311
#define USB3_TYPEC_HOST1_U3_TYPEC_HOST1_PHY_INTERRUPT_USB_INTERRUPT_TYPE    1
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_IRQ_INTERRUPT_ID                    312
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_IRQ_INTERRUPT_TYPE                  1
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_OTGIRQ_INTERRUPT_ID                 313
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_OTGIRQ_INTERRUPT_TYPE               1
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_HOST_SYSTEM_ERROR_INTERRUPT_ID      314
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_HOST_SYSTEM_ERROR_INTERRUPT_TYPE    1
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_ITP_INTERRUPT_ID                    315
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_ITP_INTERRUPT_TYPE                  3
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_PHY_INTERRUPT_DP_INTERRUPT_ID       316
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_PHY_INTERRUPT_DP_INTERRUPT_TYPE     1
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_PHY_INTERRUPT_USB_INTERRUPT_ID      317
#define USB3_TYPEC_HOST2_U3_TYPEC_HOST2_PHY_INTERRUPT_USB_INTERRUPT_TYPE    1
#define FCH_INTR_I2C0_INTERRUPT_ID                                          318
#define FCH_INTR_I2C0_INTERRUPT_TYPE                                        1
#define FCH_INTR_I2C1_INTERRUPT_ID                                          319
#define FCH_INTR_I2C1_INTERRUPT_TYPE                                        1
#define FCH_INTR_I2C2_INTERRUPT_ID                                          320
#define FCH_INTR_I2C2_INTERRUPT_TYPE                                        1
#define FCH_INTR_I2C3_INTERRUPT_ID                                          321
#define FCH_INTR_I2C3_INTERRUPT_TYPE                                        1
#define FCH_INTR_I2C4_INTERRUPT_ID                                          322
#define FCH_INTR_I2C4_INTERRUPT_TYPE                                        1
#define FCH_INTR_I2C5_INTERRUPT_ID                                          323
#define FCH_INTR_I2C5_INTERRUPT_TYPE                                        1
#define FCH_INTR_I2C6_INTERRUPT_ID                                          324
#define FCH_INTR_I2C6_INTERRUPT_TYPE                                        1
#define FCH_INTR_I2C7_INTERRUPT_ID                                          325
#define FCH_INTR_I2C7_INTERRUPT_TYPE                                        1
#define FCH_INTR_SPI0_INTERRUPT_ID                                          326
#define FCH_INTR_SPI0_INTERRUPT_TYPE                                        1
#define FCH_INTR_SPI1_INTERRUPT_ID                                          327
#define FCH_INTR_SPI1_INTERRUPT_TYPE                                        1
#define FCH_INTR_UART0_INTERRUPT_ID                                         328
#define FCH_INTR_UART0_INTERRUPT_TYPE                                       1
#define FCH_INTR_UART1_INTERRUPT_ID                                         329
#define FCH_INTR_UART1_INTERRUPT_TYPE                                       1
#define FCH_INTR_UART2_INTERRUPT_ID                                         330
#define FCH_INTR_UART2_INTERRUPT_TYPE                                       1
#define FCH_INTR_UART3_INTERRUPT_ID                                         331
#define FCH_INTR_UART3_INTERRUPT_TYPE                                       1
#define FCH_INTR_I3C0_INTERRUPT_ID                                          332
#define FCH_INTR_I3C0_INTERRUPT_TYPE                                        1
#define FCH_INTR_I3C1_INTERRUPT_ID                                          333
#define FCH_INTR_I3C1_INTERRUPT_TYPE                                        1
#define FCH_INTR_XSPI_INTERRUPT_ID                                          334
#define FCH_INTR_XSPI_INTERRUPT_TYPE                                        1
#define FCH_INTR_DMA_INTERRUPT_ID                                           335
#define FCH_INTR_DMA_INTERRUPT_TYPE                                         1
#define FCH_INTR_GPIO0_INTERRUPT_ID                                         336
#define FCH_INTR_GPIO0_INTERRUPT_TYPE                                       1
#define FCH_INTR_GPIO1_INTERRUPT_ID                                         337
#define FCH_INTR_GPIO1_INTERRUPT_TYPE                                       1
#define FCH_INTR_GPIO2_INTERRUPT_ID                                         338
#define FCH_INTR_GPIO2_INTERRUPT_TYPE                                       1
#define FCH_INTR_GPIO3_INTERRUPT_ID                                         339
#define FCH_INTR_GPIO3_INTERRUPT_TYPE                                       1
#define FCH_INTR_TIMER0_INTERRUPT_ID                                        340
#define FCH_INTR_TIMER0_INTERRUPT_TYPE                                      1
#define FCH_INTR_TIMER1_INTERRUPT_ID                                        341
#define FCH_INTR_TIMER1_INTERRUPT_TYPE                                      1
#define FCH_INTR_TIMER2_INTERRUPT_ID                                        342
#define FCH_INTR_TIMER2_INTERRUPT_TYPE                                      1
#define FCH_INTR_TIMER3_INTERRUPT_ID                                        343
#define FCH_INTR_TIMER3_INTERRUPT_TYPE                                      1
#define FCH_INTR_TIMER4_INTERRUPT_ID                                        344
#define FCH_INTR_TIMER4_INTERRUPT_TYPE                                      1
#define FCH_INTR_TIMER5_INTERRUPT_ID                                        345
#define FCH_INTR_TIMER5_INTERRUPT_TYPE                                      1
#define FCH_INTR_TIMER6_INTERRUPT_ID                                        346
#define FCH_INTR_TIMER6_INTERRUPT_TYPE                                      1
#define FCH_INTR_TIMER7_INTERRUPT_ID                                        347
#define FCH_INTR_TIMER7_INTERRUPT_TYPE                                      1
#define DPU_EXT_U_DPU0_IRQ0_INTERRUPT_ID                                    348
#define DPU_EXT_U_DPU0_IRQ0_INTERRUPT_TYPE                                  1
#define DPU_EXT_U_DPU0_IRQ1_INTERRUPT_ID                                    349
#define DPU_EXT_U_DPU0_IRQ1_INTERRUPT_TYPE                                  1
#define DPU_EXT_U_DPU1_IRQ0_INTERRUPT_ID                                    350
#define DPU_EXT_U_DPU1_IRQ0_INTERRUPT_TYPE                                  1
#define DPU_EXT_U_DPU1_IRQ1_INTERRUPT_ID                                    351
#define DPU_EXT_U_DPU1_IRQ1_INTERRUPT_TYPE                                  1
#define DPU_EXT_U_DPU2_IRQ0_INTERRUPT_ID                                    352
#define DPU_EXT_U_DPU2_IRQ0_INTERRUPT_TYPE                                  1
#define DPU_EXT_U_DPU2_IRQ1_INTERRUPT_ID                                    353
#define DPU_EXT_U_DPU2_IRQ1_INTERRUPT_TYPE                                  1
#define DPU_EXT_U_DPU3_IRQ0_INTERRUPT_ID                                    354
#define DPU_EXT_U_DPU3_IRQ0_INTERRUPT_TYPE                                  1
#define DPU_EXT_U_DPU3_IRQ1_INTERRUPT_ID                                    355
#define DPU_EXT_U_DPU3_IRQ1_INTERRUPT_TYPE                                  1
#define DPU_EXT_U_DPU4_IRQ0_INTERRUPT_ID                                    356
#define DPU_EXT_U_DPU4_IRQ0_INTERRUPT_TYPE                                  1
#define DPU_EXT_U_DPU4_IRQ1_INTERRUPT_ID                                    357
#define DPU_EXT_U_DPU4_IRQ1_INTERRUPT_TYPE                                  1
#define VPU_EXT_U_VPU_CORE_IRQ_INTERRUPT_ID                                 358
#define VPU_EXT_U_VPU_CORE_IRQ_INTERRUPT_TYPE                               1
#define NPU_EXT_U_NPU_CORE_IRQO_INTERRUPT_ID                                359
#define NPU_EXT_U_NPU_CORE_IRQO_INTERRUPT_TYPE                              1
#define ISP_EXT_U_ISP_CORE_O_ISP_INT_INTERRUPT_ID                           360
#define ISP_EXT_U_ISP_CORE_O_ISP_INT_INTERRUPT_TYPE                         1
#define ISP_EXT_U_ISP_CORE_O_ISP_INT_ABNORMAL_INTERRUPT_ID                  361
#define ISP_EXT_U_ISP_CORE_O_ISP_INT_ABNORMAL_INTERRUPT_TYPE                1
#define ISP_EXT_U_ISP_CORE_O_GDC_INT_INTERRUPT_ID                           362
#define ISP_EXT_U_ISP_CORE_O_GDC_INT_INTERRUPT_TYPE                         1
#define ISP_EXT_U_ISP_CORE_O_GDC_INT_ABNORMAL_INTERRUPT_ID                  363
#define ISP_EXT_U_ISP_CORE_O_GDC_INT_ABNORMAL_INTERRUPT_TYPE                1
#define DP_DP0_APB_INT_INTERRUPT_ID                                         364
#define DP_DP0_APB_INT_INTERRUPT_TYPE                                       1
#define DP_DP1_APB_INT_INTERRUPT_ID                                         365
#define DP_DP1_APB_INT_INTERRUPT_TYPE                                       1
#define DP_DP2_APB_INT_INTERRUPT_ID                                         366
#define DP_DP2_APB_INT_INTERRUPT_TYPE                                       1
#define DP_DP3_APB_INT_INTERRUPT_ID                                         367
#define DP_DP3_APB_INT_INTERRUPT_TYPE                                       1
#define DP_DP4_APB_INT_INTERRUPT_ID                                         368
#define DP_DP4_APB_INT_INTERRUPT_TYPE                                       1
#define DFD_SOC_ETR_BUFINTR_INTERRUPT_ID                                    369
#define DFD_SOC_ETR_BUFINTR_INTERRUPT_TYPE                                  1
#define DFD_SOC_CATU_ADDRERR_INTERRUPT_ID                                   370
#define DFD_SOC_CATU_ADDRERR_INTERRUPT_TYPE                                 1
#define DFD_GIC_O_TRIG0_EVENT_INTERRUPT_ID                                  371
#define DFD_GIC_O_TRIG0_EVENT_INTERRUPT_TYPE                                3
#define DFD_GIC_O_TRIG1_EVENT_INTERRUPT_ID                                  372
#define DFD_GIC_O_TRIG1_EVENT_INTERRUPT_TYPE                                3
#define DFD_GIC_O_TRIG2_EVENT_INTERRUPT_ID                                  373
#define DFD_GIC_O_TRIG2_EVENT_INTERRUPT_TYPE                                3
#define DFD_GIC_O_TRIG3_EVENT_INTERRUPT_ID                                  374
#define DFD_GIC_O_TRIG3_EVENT_INTERRUPT_TYPE                                3
#define GMAC_GMAC0_INTR_Q0_INTERRUPT_ID                                     375
#define GMAC_GMAC0_INTR_Q0_INTERRUPT_TYPE                                   1
#define GMAC_GMAC0_INTR_Q1_INTERRUPT_ID                                     376
#define GMAC_GMAC0_INTR_Q1_INTERRUPT_TYPE                                   1
#define GMAC_GMAC0_INTR_Q2_INTERRUPT_ID                                     377
#define GMAC_GMAC0_INTR_Q2_INTERRUPT_TYPE                                   1
#define GMAC_GMAC0_INTR_Q3_INTERRUPT_ID                                     378
#define GMAC_GMAC0_INTR_Q3_INTERRUPT_TYPE                                   1
#define GMAC_GMAC0_INTR_Q4_INTERRUPT_ID                                     379
#define GMAC_GMAC0_INTR_Q4_INTERRUPT_TYPE                                   1
#define GMAC_GMAC0_INTR_Q5_INTERRUPT_ID                                     380
#define GMAC_GMAC0_INTR_Q5_INTERRUPT_TYPE                                   1
#define GMAC_GMAC0_INTR_Q6_INTERRUPT_ID                                     381
#define GMAC_GMAC0_INTR_Q6_INTERRUPT_TYPE                                   1
#define GMAC_GMAC0_INTR_Q7_INTERRUPT_ID                                     382
#define GMAC_GMAC0_INTR_Q7_INTERRUPT_TYPE                                   1
#define GMAC_GMAC1_INTR_Q0_INTERRUPT_ID                                     383
#define GMAC_GMAC1_INTR_Q0_INTERRUPT_TYPE                                   1
#define GMAC_GMAC1_INTR_Q1_INTERRUPT_ID                                     384
#define GMAC_GMAC1_INTR_Q1_INTERRUPT_TYPE                                   1
#define GMAC_GMAC1_INTR_Q2_INTERRUPT_ID                                     385
#define GMAC_GMAC1_INTR_Q2_INTERRUPT_TYPE                                   1
#define GMAC_GMAC1_INTR_Q3_INTERRUPT_ID                                     386
#define GMAC_GMAC1_INTR_Q3_INTERRUPT_TYPE                                   1
#define GMAC_GMAC1_INTR_Q4_INTERRUPT_ID                                     387
#define GMAC_GMAC1_INTR_Q4_INTERRUPT_TYPE                                   1
#define GMAC_GMAC1_INTR_Q5_INTERRUPT_ID                                     388
#define GMAC_GMAC1_INTR_Q5_INTERRUPT_TYPE                                   1
#define GMAC_GMAC1_INTR_Q6_INTERRUPT_ID                                     389
#define GMAC_GMAC1_INTR_Q6_INTERRUPT_TYPE                                   1
#define GMAC_GMAC1_INTR_Q7_INTERRUPT_ID                                     390
#define GMAC_GMAC1_INTR_Q7_INTERRUPT_TYPE                                   1
#define CSU_PM_INT_CALLEE_MAILBOX1_INTERRUPT_ID                             391
#define CSU_PM_INT_CALLEE_MAILBOX1_INTERRUPT_TYPE                           1
#define CSU_PM_INT_CALLEE_MAILBOX3_INTERRUPT_ID                             392
#define CSU_PM_INT_CALLEE_MAILBOX3_INTERRUPT_TYPE                           1
#define CSU_PM_INT_CALLEE_MAILBOX5_INTERRUPT_ID                             393
#define CSU_PM_INT_CALLEE_MAILBOX5_INTERRUPT_TYPE                           1
#define CSU_PM_INT_CALLEE_MAILBOX7_INTERRUPT_ID                             394
#define CSU_PM_INT_CALLEE_MAILBOX7_INTERRUPT_TYPE                           1
#define CSU_PM_INT_CALLER_MAILBOX0_INTERRUPT_ID                             395
#define CSU_PM_INT_CALLER_MAILBOX0_INTERRUPT_TYPE                           1
#define CSU_PM_INT_CALLER_MAILBOX2_INTERRUPT_ID                             396
#define CSU_PM_INT_CALLER_MAILBOX2_INTERRUPT_TYPE                           1
#define CSU_PM_INT_CALLER_MAILBOX4_INTERRUPT_ID                             397
#define CSU_PM_INT_CALLER_MAILBOX4_INTERRUPT_TYPE                           1
#define CSU_PM_INT_CALLER_MAILBOX6_INTERRUPT_ID                             398
#define CSU_PM_INT_CALLER_MAILBOX6_INTERRUPT_TYPE                           1
#define CSU_PM_PM_I2C_IRQ_0_INTERRUPT_ID                                    399
#define CSU_PM_PM_I2C_IRQ_0_INTERRUPT_TYPE                                  1
#define CSU_PM_PM_I2C_IRQ_1_INTERRUPT_ID                                    400
#define CSU_PM_PM_I2C_IRQ_1_INTERRUPT_TYPE                                  1
#define CSU_PM_PM_I2C_IRQ_2_INTERRUPT_ID                                    401
#define CSU_PM_PM_I2C_IRQ_2_INTERRUPT_TYPE                                  1
#define CSU_PM_PM_I2C_IRQ_3_INTERRUPT_ID                                    402
#define CSU_PM_PM_I2C_IRQ_3_INTERRUPT_TYPE                                  1
#define CSU_PM_PROCHOT_INTR_INTERRUPT_ID                                    403
#define CSU_PM_PROCHOT_INTR_INTERRUPT_TYPE                                  1
#define S5_SS_U0_CDNSGPIO_GPIO_INT_INTERRUPT_ID                             404
#define S5_SS_U0_CDNSGPIO_GPIO_INT_INTERRUPT_TYPE                           1
#define S5_SS_U1_CDNSGPIO_GPIO_INT_INTERRUPT_ID                             405
#define S5_SS_U1_CDNSGPIO_GPIO_INT_INTERRUPT_TYPE                           1
#define S5_SS_U2_CDNSGPIO_GPIO_INT_INTERRUPT_ID                             406
#define S5_SS_U2_CDNSGPIO_GPIO_INT_INTERRUPT_TYPE                           1
#define S5_SS_PM_INTR_INTERRUPT_ID                                          407
#define S5_SS_PM_INTR_INTERRUPT_TYPE                                        1
#define S5_SS_SYSWDT_INTR_INTERRUPT_ID                                      408
#define S5_SS_SYSWDT_INTR_INTERRUPT_TYPE                                    1
#define CSU_SE_INTR_STAR_LOCKUP_VDCI_OUT_INTERRUPT_ID                       409
#define CSU_SE_INTR_STAR_LOCKUP_VDCI_OUT_INTERRUPT_TYPE                     1
#define CSU_SE_INTR_MAILB0_CALLER_INTERRUPT_ID                              410
#define CSU_SE_INTR_MAILB0_CALLER_INTERRUPT_TYPE                            1
#define CSU_SE_INTR_MAILB1_CALLEE_INTERRUPT_ID                              411
#define CSU_SE_INTR_MAILB1_CALLEE_INTERRUPT_TYPE                            1
#define CSU_SE_INTR_MAILB2_CALLER_INTERRUPT_ID                              412
#define CSU_SE_INTR_MAILB2_CALLER_INTERRUPT_TYPE                            1
#define CSU_SE_INTR_MAILB3_CALLEE_INTERRUPT_ID                              413
#define CSU_SE_INTR_MAILB3_CALLEE_INTERRUPT_TYPE                            1
#define CSU_SE_INTR_MAILB4_CALLER_INTERRUPT_ID                              414
#define CSU_SE_INTR_MAILB4_CALLER_INTERRUPT_TYPE                            1
#define CSU_SE_INTR_MAILB5_CALLEE_INTERRUPT_ID                              415
#define CSU_SE_INTR_MAILB5_CALLEE_INTERRUPT_TYPE                            1
#define CSU_SE_INTR_MAILB6_CALLER_INTERRUPT_ID                              416
#define CSU_SE_INTR_MAILB6_CALLER_INTERRUPT_TYPE                            1
#define CSU_SE_INTR_MAILB7_CALLEE_INTERRUPT_ID                              417
#define CSU_SE_INTR_MAILB7_CALLEE_INTERRUPT_TYPE                            1
#define CSU_SE_INTR_UART1_INTERRUPT_ID                                      418
#define CSU_SE_INTR_UART1_INTERRUPT_TYPE                                    1
#define CSU_SE_INTR_UART0_INTERRUPT_ID                                      419
#define CSU_SE_INTR_UART0_INTERRUPT_TYPE                                    1
#define CSU_SE_CSU_SE_WDG_WDOGINT_INTERRUPT_ID                              420
#define CSU_SE_CSU_SE_WDG_WDOGINT_INTERRUPT_TYPE                            1
#define CSU_SE_CSU_SE_STAR_CTIIRQ_VDCI_OUT1_INTERRUPT_ID                    421
#define CSU_SE_CSU_SE_STAR_CTIIRQ_VDCI_OUT1_INTERRUPT_TYPE                  1
#define CSU_SE_CSU_SE_STAR_CTIIRQ_VDCI_OUT0_INTERRUPT_ID                    422
#define CSU_SE_CSU_SE_STAR_CTIIRQ_VDCI_OUT0_INTERRUPT_TYPE                  1
#define SENSOR_FUSION_INTR_MAILB0_CALLEE_INTERRUPT_ID                       423
#define SENSOR_FUSION_INTR_MAILB0_CALLEE_INTERRUPT_TYPE                     1
#define SENSOR_FUSION_INTR_MAILB1_CALLER_INTERRUPT_ID                       424
#define SENSOR_FUSION_INTR_MAILB1_CALLER_INTERRUPT_TYPE                     1
#define SENSOR_FUSION_INTR_WDOGRES_INTERRUPT_ID                             425
#define SENSOR_FUSION_INTR_WDOGRES_INTERRUPT_TYPE                           1
#define SENSOR_FUSION_INTR_SPI_INTERRUPT_ID                                 426
#define SENSOR_FUSION_INTR_SPI_INTERRUPT_TYPE                               1
#define SENSOR_FUSION_INTR_I3C1_INTERRUPT_ID                                427
#define SENSOR_FUSION_INTR_I3C1_INTERRUPT_TYPE                              1
#define SENSOR_FUSION_INTR_I3C0_INTERRUPT_ID                                428
#define SENSOR_FUSION_INTR_I3C0_INTERRUPT_TYPE                              1
#define SENSOR_FUSION_INTR_I2C1_INTERRUPT_ID                                429
#define SENSOR_FUSION_INTR_I2C1_INTERRUPT_TYPE                              1
#define SENSOR_FUSION_INTR_I2C0_INTERRUPT_ID                                430
#define SENSOR_FUSION_INTR_I2C0_INTERRUPT_TYPE                              1
#define SENSOR_FUSION_CTIIRQ1_INTERRUPT_ID                                  431
#define SENSOR_FUSION_CTIIRQ1_INTERRUPT_TYPE                                1
#define SENSOR_FUSION_CTIIRQ0_INTERRUPT_ID                                  432
#define SENSOR_FUSION_CTIIRQ0_INTERRUPT_TYPE                                1
#define SENSOR_FUSION_INTR_SW_DEFINE_INTERRUPT_ID                           433
#define SENSOR_FUSION_INTR_SW_DEFINE_INTERRUPT_TYPE                         1
#define PCIE_SUBSYS_X8_CORRECTABLE_ERROR_OUT_INTERRUPT_ID                   434
#define PCIE_SUBSYS_X8_CORRECTABLE_ERROR_OUT_INTERRUPT_TYPE                 3
#define PCIE_SUBSYS_X8_FATAL_ERROR_OUT_INTERRUPT_ID                         435
#define PCIE_SUBSYS_X8_FATAL_ERROR_OUT_INTERRUPT_TYPE                       3
#define PCIE_SUBSYS_X8_NON_FATAL_ERROR_OUT_INTERRUPT_ID                     436
#define PCIE_SUBSYS_X8_NON_FATAL_ERROR_OUT_INTERRUPT_TYPE                   3
#define PCIE_SUBSYS_X8_LOCAL_INTERRUPT_INTERRUPT_ID                         437
#define PCIE_SUBSYS_X8_LOCAL_INTERRUPT_INTERRUPT_TYPE                       1
#define PCIE_SUBSYS_X8_PHY_INTERRUPT_OUT_INTERRUPT_ID                       438
#define PCIE_SUBSYS_X8_PHY_INTERRUPT_OUT_INTERRUPT_TYPE                     1
#define PCIE_SUBSYS_X8_INTX_OUT0_INTERRUPT_ID                               439
#define PCIE_SUBSYS_X8_INTX_OUT0_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X8_INTX_OUT1_INTERRUPT_ID                               440
#define PCIE_SUBSYS_X8_INTX_OUT1_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X8_INTX_OUT2_INTERRUPT_ID                               441
#define PCIE_SUBSYS_X8_INTX_OUT2_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X8_INTX_OUT3_INTERRUPT_ID                               442
#define PCIE_SUBSYS_X8_INTX_OUT3_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X8_PHY_STATE_CHG_STS_P_0_INTERRUPT_ID                   443
#define PCIE_SUBSYS_X8_PHY_STATE_CHG_STS_P_0_INTERRUPT_TYPE                 3
#define PCIE_SUBSYS_X4_CORRECTABLE_ERROR_OUT_INTERRUPT_ID                   444
#define PCIE_SUBSYS_X4_CORRECTABLE_ERROR_OUT_INTERRUPT_TYPE                 3
#define PCIE_SUBSYS_X4_FATAL_ERROR_OUT_INTERRUPT_ID                         445
#define PCIE_SUBSYS_X4_FATAL_ERROR_OUT_INTERRUPT_TYPE                       3
#define PCIE_SUBSYS_X4_NON_FATAL_ERROR_OUT_INTERRUPT_ID                     446
#define PCIE_SUBSYS_X4_NON_FATAL_ERROR_OUT_INTERRUPT_TYPE                   1
#define PCIE_SUBSYS_X4_LOCAL_INTERRUPT_INTERRUPT_ID                         447
#define PCIE_SUBSYS_X4_LOCAL_INTERRUPT_INTERRUPT_TYPE                       1
#define PCIE_SUBSYS_X4_PHY_INTERRUPT_OUT_INTERRUPT_ID                       448
#define PCIE_SUBSYS_X4_PHY_INTERRUPT_OUT_INTERRUPT_TYPE                     1
#define PCIE_SUBSYS_X4_INTX_OUT0_INTERRUPT_ID                               449
#define PCIE_SUBSYS_X4_INTX_OUT0_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X4_INTX_OUT1_INTERRUPT_ID                               450
#define PCIE_SUBSYS_X4_INTX_OUT1_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X4_INTX_OUT2_INTERRUPT_ID                               451
#define PCIE_SUBSYS_X4_INTX_OUT2_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X4_INTX_OUT3_INTERRUPT_ID                               452
#define PCIE_SUBSYS_X4_INTX_OUT3_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X4_PHY_STATE_CHG_STS_P_0_INTERRUPT_ID                   453
#define PCIE_SUBSYS_X4_PHY_STATE_CHG_STS_P_0_INTERRUPT_TYPE                 1
#define PCIE_SUBSYS_X2_CORRECTABLE_ERROR_OUT_INTERRUPT_ID                   454
#define PCIE_SUBSYS_X2_CORRECTABLE_ERROR_OUT_INTERRUPT_TYPE                 3
#define PCIE_SUBSYS_X2_FATAL_ERROR_OUT_INTERRUPT_ID                         455
#define PCIE_SUBSYS_X2_FATAL_ERROR_OUT_INTERRUPT_TYPE                       3
#define PCIE_SUBSYS_X2_NON_FATAL_ERROR_OUT_INTERRUPT_ID                     456
#define PCIE_SUBSYS_X2_NON_FATAL_ERROR_OUT_INTERRUPT_TYPE                   3
#define PCIE_SUBSYS_X2_LOCAL_INTERRUPT_INTERRUPT_ID                         457
#define PCIE_SUBSYS_X2_LOCAL_INTERRUPT_INTERRUPT_TYPE                       1
#define PCIE_SUBSYS_X2_PHY_INTERRUPT_OUT_INTERRUPT_ID                       458
#define PCIE_SUBSYS_X2_PHY_INTERRUPT_OUT_INTERRUPT_TYPE                     1
#define PCIE_SUBSYS_X2_INTX_OUT0_INTERRUPT_ID                               459
#define PCIE_SUBSYS_X2_INTX_OUT0_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X2_INTX_OUT1_INTERRUPT_ID                               460
#define PCIE_SUBSYS_X2_INTX_OUT1_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X2_INTX_OUT2_INTERRUPT_ID                               461
#define PCIE_SUBSYS_X2_INTX_OUT2_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X2_INTX_OUT3_INTERRUPT_ID                               462
#define PCIE_SUBSYS_X2_INTX_OUT3_INTERRUPT_TYPE                             1
#define PCIE_SUBSYS_X1_0_CORRECTABLE_ERROR_OUT_INTERRUPT_ID                 463
#define PCIE_SUBSYS_X1_0_CORRECTABLE_ERROR_OUT_INTERRUPT_TYPE               3
#define PCIE_SUBSYS_X1_0_FATAL_ERROR_OUT_INTERRUPT_ID                       464
#define PCIE_SUBSYS_X1_0_FATAL_ERROR_OUT_INTERRUPT_TYPE                     3
#define PCIE_SUBSYS_X1_0_NON_FATAL_ERROR_OUT_INTERRUPT_ID                   465
#define PCIE_SUBSYS_X1_0_NON_FATAL_ERROR_OUT_INTERRUPT_TYPE                 3
#define PCIE_SUBSYS_X1_0_LOCAL_INTERRUPT_INTERRUPT_ID                       466
#define PCIE_SUBSYS_X1_0_LOCAL_INTERRUPT_INTERRUPT_TYPE                     1
#define PCIE_SUBSYS_X1_0_PHY_INTERRUPT_OUT_INTERRUPT_ID                     467
#define PCIE_SUBSYS_X1_0_PHY_INTERRUPT_OUT_INTERRUPT_TYPE                   1
#define PCIE_SUBSYS_X1_0_INTX_OUT0_INTERRUPT_ID                             468
#define PCIE_SUBSYS_X1_0_INTX_OUT0_INTERRUPT_TYPE                           1
#define PCIE_SUBSYS_X1_0_INTX_OUT1_INTERRUPT_ID                             469
#define PCIE_SUBSYS_X1_0_INTX_OUT1_INTERRUPT_TYPE                           1
#define PCIE_SUBSYS_X1_0_INTX_OUT2_INTERRUPT_ID                             470
#define PCIE_SUBSYS_X1_0_INTX_OUT2_INTERRUPT_TYPE                           1
#define PCIE_SUBSYS_X1_0_INTX_OUT3_INTERRUPT_ID                             471
#define PCIE_SUBSYS_X1_0_INTX_OUT3_INTERRUPT_TYPE                           1
#define PCIE_SUBSYS_X1_1_CORRECTABLE_ERROR_OUT_INTERRUPT_ID                 472
#define PCIE_SUBSYS_X1_1_CORRECTABLE_ERROR_OUT_INTERRUPT_TYPE               3
#define PCIE_SUBSYS_X1_1_FATAL_ERROR_OUT_INTERRUPT_ID                       473
#define PCIE_SUBSYS_X1_1_FATAL_ERROR_OUT_INTERRUPT_TYPE                     3
#define PCIE_SUBSYS_X1_1_NON_FATAL_ERROR_OUT_INTERRUPT_ID                   474
#define PCIE_SUBSYS_X1_1_NON_FATAL_ERROR_OUT_INTERRUPT_TYPE                 3
#define PCIE_SUBSYS_X1_1_LOCAL_INTERRUPT_INTERRUPT_ID                       475
#define PCIE_SUBSYS_X1_1_LOCAL_INTERRUPT_INTERRUPT_TYPE                     1
#define PCIE_SUBSYS_X1_1_PHY_INTERRUPT_OUT_INTERRUPT_ID                     476
#define PCIE_SUBSYS_X1_1_PHY_INTERRUPT_OUT_INTERRUPT_TYPE                   1
#define PCIE_SUBSYS_X1_1_INTX_OUT0_INTERRUPT_ID                             477
#define PCIE_SUBSYS_X1_1_INTX_OUT0_INTERRUPT_TYPE                           1
#define PCIE_SUBSYS_X1_1_INTX_OUT1_INTERRUPT_ID                             478
#define PCIE_SUBSYS_X1_1_INTX_OUT1_INTERRUPT_TYPE                           1
#define PCIE_SUBSYS_X1_1_INTX_OUT2_INTERRUPT_ID                             479
#define PCIE_SUBSYS_X1_1_INTX_OUT2_INTERRUPT_TYPE                           1
#define PCIE_SUBSYS_X1_1_INTX_OUT3_INTERRUPT_ID                             480
#define PCIE_SUBSYS_X1_1_INTX_OUT3_INTERRUPT_TYPE                           1
#define PCIE_SUBSYS_X2_1_1_PHY_STATE_CHG_STS_P_0_INTERRUPT_ID               481
#define PCIE_SUBSYS_X2_1_1_PHY_STATE_CHG_STS_P_0_INTERRUPT_TYPE             1
#define PCIE_SUBSYS_X2_1_1_PHY_STATE_CHG_STS_P_1_INTERRUPT_ID               482
#define PCIE_SUBSYS_X2_1_1_PHY_STATE_CHG_STS_P_1_INTERRUPT_TYPE             1
#define PCIE_SUBSYS_X2_1_1_PHY_STATE_CHG_STS_P_2_INTERRUPT_ID               483
#define PCIE_SUBSYS_X2_1_1_PHY_STATE_CHG_STS_P_2_INTERRUPT_TYPE             1
#define CSI_IRQ0_INTERRUPT_ID                                               484
#define CSI_IRQ0_INTERRUPT_TYPE                                             1
#define CSI_ERR_IRQ0_INTERRUPT_ID                                           485
#define CSI_ERR_IRQ0_INTERRUPT_TYPE                                         1
#define CSI_IRQ1_INTERRUPT_ID                                               486
#define CSI_IRQ1_INTERRUPT_TYPE                                             1
#define CSI_ERR_IRQ1_INTERRUPT_ID                                           487
#define CSI_ERR_IRQ1_INTERRUPT_TYPE                                         1
#define CSI_IRQ2_INTERRUPT_ID                                               488
#define CSI_IRQ2_INTERRUPT_TYPE                                             1
#define CSI_ERR_IRQ2_INTERRUPT_ID                                           489
#define CSI_ERR_IRQ2_INTERRUPT_TYPE                                         1
#define CSI_IRQ3_INTERRUPT_ID                                               490
#define CSI_IRQ3_INTERRUPT_TYPE                                             1
#define CSI_ERR_IRQ3_INTERRUPT_ID                                           491
#define CSI_ERR_IRQ3_INTERRUPT_TYPE                                         1
#define CSI_CSI_BRIDGE_ERR_IRQ0_INTERRUPT_ID                                492
#define CSI_CSI_BRIDGE_ERR_IRQ0_INTERRUPT_TYPE                              1
#define CSI_CSI_BRIDGE_ERR_IRQ1_INTERRUPT_ID                                493
#define CSI_CSI_BRIDGE_ERR_IRQ1_INTERRUPT_TYPE                              1
#define CSI_CSI_BRIDGE_ERR_IRQ2_INTERRUPT_ID                                494
#define CSI_CSI_BRIDGE_ERR_IRQ2_INTERRUPT_TYPE                              1
#define CSI_CSI_BRIDGE_ERR_IRQ3_INTERRUPT_ID                                495
#define CSI_CSI_BRIDGE_ERR_IRQ3_INTERRUPT_TYPE                              1
#define IO_S0_IO_TOP_S0_PROCHOT_L_IN_INTERRUPT_ID                           496
#define IO_S0_IO_TOP_S0_PROCHOT_L_IN_INTERRUPT_TYPE                         1 // In Sky1_Interrrupt_IntID_Mapping the Value is Level-Low
#define PCIE_SUBSYS_X8_PCIE_EP_INTERRUPT_ID                                 497
#define PCIE_SUBSYS_X8_PCIE_EP_INTERRUPT_TYPE                               1
#define FCH_INTR_TIMER8_INTERRUPT_ID                                        498
#define FCH_INTR_TIMER8_INTERRUPT_TYPE                                      1
#define FCH_INTR_TIMER9_INTERRUPT_ID                                        499
#define FCH_INTR_TIMER9_INTERRUPT_TYPE                                      1
#define FCH_INTR_TIMER10_INTERRUPT_ID                                       500
#define FCH_INTR_TIMER10_INTERRUPT_TYPE                                     1
#define FCH_INTR_TIMER11_INTERRUPT_ID                                       501
#define FCH_INTR_TIMER11_INTERRUPT_TYPE                                     1
#define FCH_INTR_TIMER12_INTERRUPT_ID                                       502
#define FCH_INTR_TIMER12_INTERRUPT_TYPE                                     1
#define FCH_INTR_TIMER13_INTERRUPT_ID                                       503
#define FCH_INTR_TIMER13_INTERRUPT_TYPE                                     1
#define FCH_INTR_TIMER14_INTERRUPT_ID                                       504
#define FCH_INTR_TIMER14_INTERRUPT_TYPE                                     1
#define CSU_SE_S0_DUMMY_OUT2_INTERRUPT_ID                                   505
#define CSU_SE_S0_DUMMY_OUT2_INTERRUPT_TYPE                                 1
#define CSU_SE_S0_DUMMY_OUT3_INTERRUPT_ID                                   506
#define CSU_SE_S0_DUMMY_OUT3_INTERRUPT_TYPE                                 1

#endif
